"""create recipes

Revision ID: 14628a1823ca
Revises: 
Create Date: 2026-05-28 12:00:14.639632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14628a1823ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('time', sa.String(length=100), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('cooking', sa.JSON(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_title'))
        batch_op.drop_index(batch_op.f('ix_recipes_category'))

    op.drop_table('recipes')
    # ### end Alembic commands ###
